In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!sudo apt-get install unzip

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unzip is already the newest version (6.0-26ubuntu3.2).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.


In [3]:
!unzip /content/drive/MyDrive/spn/Rapid-SPN-master.zip
!unzip /content/drive/MyDrive/spn/SPFlow-master.zip

Archive:  /content/drive/MyDrive/spn/Rapid-SPN-master.zip
62e8688262f99c4e0f2cb2e28249fb690969e898
   creating: Rapid-SPN-master/
  inflating: Rapid-SPN-master/.gitignore  
 extracting: Rapid-SPN-master/.gitmodules  
  inflating: Rapid-SPN-master/LICENSE  
  inflating: Rapid-SPN-master/README.md  
   creating: Rapid-SPN-master/scripts/
  inflating: Rapid-SPN-master/scripts/.DS_Store  
  inflating: Rapid-SPN-master/scripts/balance_scale.py  
  inflating: Rapid-SPN-master/scripts/blood.py  
  inflating: Rapid-SPN-master/scripts/bodyfat.py  
  inflating: Rapid-SPN-master/scripts/calculate.py  
  inflating: Rapid-SPN-master/scripts/car.py  
  inflating: Rapid-SPN-master/scripts/cifar_10.py  
  inflating: Rapid-SPN-master/scripts/cifar_10_spnrp.py  
  inflating: Rapid-SPN-master/scripts/cifar_10_spnrp_height.py  
  inflating: Rapid-SPN-master/scripts/cifar_bash.sh  
  inflating: Rapid-SPN-master/scripts/cifar_pca.py  
  inflating: Rapid-SPN-master/scripts/cv_10_ll.py  
  inflating: Rapid-SP

In [4]:
!mv Rapid-SPN-master/ spn
!mv SPFlow-master/ spflow

In [5]:
!ls

drive  sample_data  spflow  spn


One time initialization of Google Colab Completed

In [6]:
%cd /content/spflow/src/
!sh create_pip_dist.sh


/content/spflow/src
Creating package
running sdist
running egg_info
creating spflow.egg-info
writing spflow.egg-info/PKG-INFO
writing dependency_links to spflow.egg-info/dependency_links.txt
writing requirements to spflow.egg-info/requires.txt
writing top-level names to spflow.egg-info/top_level.txt
writing manifest file 'spflow.egg-info/SOURCES.txt'
reading manifest file 'spflow.egg-info/SOURCES.txt'
writing manifest file 'spflow.egg-info/SOURCES.txt'

running check
creating spflow-0.0.40
creating spflow-0.0.40/spflow.egg-info
creating spflow-0.0.40/spn
creating spflow-0.0.40/spn/algorithms
creating spflow-0.0.40/spn/algorithms/layerwise
creating spflow-0.0.40/spn/algorithms/measures
creating spflow-0.0.40/spn/algorithms/splitting
creating spflow-0.0.40/spn/algorithms/stats
creating spflow-0.0.40/spn/data
creating spflow-0.0.40/spn/experiments
creating spflow-0.0.40/spn/experiments/AQP
creating spflow-0.0.40/spn/experiments/AQP/expectation
creating spflow-0.0.40/spn/experiments/AQP/le

In [7]:
!pip install dist/spflow-0.0.40-py3-none-any.whl #restarts directory

Processing ./dist/spflow-0.0.40-py3-none-any.whl
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 49.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.5/103.5 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 92.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 MB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.5/270.5 kB 20.9 MB/s eta 0:00:00
  Created wheel for arff: filename=arff-0.9-py3-none-any.whl size=4949 sha256=2a31e026e20e3fa32ee299aff53083fe538fa73743119a72c9d2599b21f93578
  Stored in directory: /root/.cache/pip/wheels/0c/39/12/4d8ff491018bce2dd9cc6034298f27399c7f4fd4063187f7be
  Created wheel for ete3: filename=ete3-3.1.3-py3-none-any.whl size=2273787 sha256=4c49e66d76d7221124bf4a899ab9b72f8147e32c049745bcfe59051aa179f5c5
  Stored in directory: /root/.cache/pip/wheels/a0/72/00/1982bd848e52b03079d

In [1]:
%cd /content/spn

/content/spn


In [2]:
!pip install libsvm
!pip install scipy==1.11.4

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.6/170.6 kB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for libsvm: filename=libsvm-3.23.0.4-cp310-cp310-linux_x86_64.whl size=251404 sha256=26225b99a83f20678aeb18d99edc8b43f748c82024cc36af53baa26093491a4d
  Stored in directory: /root/.cache/pip/wheels/79/c7/19/a8c85928f8e629654b8e1adb3c8091f0bb77344d0ee9954a85
Successfully built libsvm
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 49.0 MB/s eta 0:00:00
  Attempting uninstall: scipy
    Found existing installation: scipy 1.13.1
    Uninstalling scipy-1.13.1:
      Successfully uninstalled scipy-1.13.1


In [3]:
%cd /content/spn/

/content/spn


In [4]:
#!/usr/bin/env python
#2839,180
import numpy
import sys
import os
from sklearn import preprocessing
from sklearn.datasets import load_svmlight_file
from sklearn.model_selection import train_test_split
from libsvm.svmutil import *
from scipy.stats._result_classes import FitResult
from spn.structure.Base import Context
from spn.io.Graphics import plot_spn
from spn.algorithms.Sampling import sample_instances
from spn.structure.leaves.parametric.Parametric import Categorical, Gaussian
from spn.algorithms.Inference import log_likelihood
from spn.algorithms.splitting.RDC import get_split_cols_RDC_py, get_split_rows_RDC_py
from sklearn.datasets import load_iris,load_digits,fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from spn.algorithms.LearningWrappers import learn_parametric
from spn.structure.Base import Product, Sum, assign_ids, rebuild_scopes_bottom_up
from sklearn.metrics import accuracy_score
from numpy.random.mtrand import RandomState
from spn.algorithms.LearningWrappers import learn_parametric, learn_classifier
from spn.algorithms.TransformStructure import Prune,Compress,SPN_Reshape
import urllib
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import fetch_openml
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold
from spn.structure.Base import *
import time;
import numpy as np, numpy.random
numpy.random.seed(42)
import multiprocessing
import traceback;
import logging
import subprocess
from numpy.random.mtrand import RandomState
#tf.logging.set_verbosity(tf.logging.INFO)
logging.getLogger().setLevel(logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))
import pickle
import time;
import numpy as np, numpy.random
from spn.algorithms.Sampling import sample_instances
MODEL_DIR='models/dna/'
FILE_NAME_DIR='models/dna/error'
from sklearn.decomposition import PCA
def train_spn_pca(X,X_test,context,height=2,prob=0.5,leaves_size=20,min_instance_slice=40,bandwidth=0.2,epochs=1000,selector_array=[2,3,4],threshold=1,use_optimizer=True,predict_bandwidth=0.4):
    try:
        print(selector_array)
        print(X.shape)
        print(X_test.shape)
        ds_context = Context(parametric_types=context).add_domains(X)
        original = time.time();
        spn =  learn_parametric(numpy.array(X),ds_context,min_instances_slice=min_instance_slice,threshold=threshold)
        ours_time = time.time()-original
        print("Buiding tree complete")
        ll_test=log_likelihood(spn,X_test)
        print(ll_test)
        print(ll_test)
        sample = np.asarray([np.nan]*X_test.shape[1]*X_test.shape[0]).reshape(X_test.shape[0],X_test.shape[1]) #change the shape to no of components
        print(sample.shape)
        sample = sample_instances(spn,sample,rand_gen=RandomState(42))
        #spn=optimize_tf(spn,X,epochs=epochs,optimizer= tf.train.AdamOptimizer(0.00001))
        #plot_spn(spn,'spnrp.png')
        print(sample.shape)
        del spn;
        return np.mean(ll_test),ours_time,sample
    except:
        f=open(FILE_NAME_DIR+'error.log','a')
        f.write(traceback.format_exc()+"\n")
        traceback.print_exc()
        f.flush()
        f.close()
        return 0,0

# experiment.py train.csv test.csv context.npy instance_slice epochs height prob leaves_size

train_dataset,labels= fetch_openml(name='CIFAR_10', version=1,return_X_y=True)
print('download complete')

download complete


In [5]:
train_dataset = train_dataset.sample(5000)
train_dataset = train_dataset.values[:,:100]
kf = KFold(n_splits=10,shuffle=True)
theirs = list()
ours = list()
ours_time_list = list()
theirs_time_list = list();
train_set = list()
test_set = list();
counter = 0;
context = list()

#parameters
output_file_name='cifar_pca.10.csv'
min_instance_slice=40
epochs=8000
height=1
prob=0.4
leaves_size=30
threshold =0.4

pca = PCA(n_components=40)

train_sample_input ,test_sample_input = train_test_split(train_dataset,test_size=0.60)
#################################################Build-Context########################################
context = []
scaler = preprocessing.MinMaxScaler();
scaler_model = scaler.fit(train_sample_input)
train_sample_normalized = preprocessing.normalize(train_sample_input)
test_sample_normalized = preprocessing.normalize(test_sample_input)
pca_component_train = pca.fit(train_sample_normalized)
pca_component_test = pca.fit(test_sample_normalized)
train_sample = pca_component_train.fit_transform(train_sample_normalized)
test_sample = pca_component_test.transform(test_sample_normalized)

In [6]:
print(test_sample.shape)
print(train_sample.shape)
for i in range(0,train_sample.shape[1]):
        context.append(Gaussian)
print(test_sample.shape)
print(len(context))
ds_context = Context(parametric_types=context).add_domains(np.asarray(train_sample))
spnrp_mean,spnrp_time,sample = train_spn_pca(X=np.asarray(train_sample),X_test=np.asarray(test_sample),context=context,height=height,leaves_size=leaves_size,threshold=threshold)
print(sample.shape)
#test_dataset = pca_component_test.inverse_transform(test_sample)
#create models directory
#calculate log likelihood of the dataset later on




(3000, 40)
(2000, 40)
(3000, 40)
40
[2, 3, 4]
(2000, 40)
(3000, 40)


/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:113: ConvergenceWarning: Maximum number of iterations reached
  warnings.warn("Maximum number of iterations reached", ConvergenceWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:113: ConvergenceWarning: Maximum number of iterations reached
  warnings.warn("Maximum number of iterations reached", ConvergenceWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:113: ConvergenceWarning: Maximum number of iterations reached
  warnings.warn("Maximum number of iterations reached", ConvergenceWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:113: ConvergenceWarning: Maximum number of iterations reached
  warnings.warn("Maximum number of iterations reached", ConvergenceWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/cross_decomposition/_pls.py:113: ConvergenceWarning: Maximum number of iterations reached
  warn

Buiding tree complete
[[106.62656988]
 [ 77.40552195]
 [ 39.74530462]
 ...
 [ 84.37152098]
 [113.85904422]
 [ 74.40777886]]
[[106.62656988]
 [ 77.40552195]
 [ 39.74530462]
 ...
 [ 84.37152098]
 [113.85904422]
 [ 74.40777886]]
(3000, 40)
(3000, 40)
(3000, 40)


In [7]:
#invese pca
model_sample_inverse_pca = pca_component_test.inverse_transform(sample)
#inverse scalar
model_sample_scalar = scaler.inverse_transform(model_sample_inverse_pca)

In [8]:
model_sample_scalar.shape

(3000, 100)

In [9]:
print(model_sample_scalar.shape)
print(test_sample_input.shape)

(3000, 100)
(3000, 100)


In [12]:
print(f'SPN Mean:{spnrp_mean}')

SPN Mean:104.2556973976924


In [13]:
sys.path.append('scripts/')
from spatialtree import *

In [14]:
print(train_sample_input.shape)
spn_context = []
for i in range(0,train_sample_input.shape[1]):
        spn_context.append(Gaussian)
spn_context = Context(parametric_types=spn_context).add_domains(np.asarray(train_sample_input))


(2000, 100)


In [15]:
T = SPNRPBuilder(data=numpy.array(train_sample_input),ds_context=spn_context,bandwidth=0.2,target=test_sample_input,prob=0.5,threshold=1,leaves_size=leaves_size,height=height,spill=0.3,selector_array=[2,3,4],use_optimizer=True,predict_bandwidth=0.4)
T= T.build_spn();
T.update_ids()
spn=T.spn_node

Sum Node  called
complete
called-1
called-1


In [16]:
spnrp_generated_sample_holder = np.asarray([np.nan]*test_sample_input.shape[1]*test_sample_input.shape[0]).reshape(test_sample_input.shape[0],test_sample_input.shape[1]) #change the shape to no of components
print(spnrp_generated_sample_holder.shape)
spnrp_generated_sample = sample_instances(spn,spnrp_generated_sample_holder,rand_gen=RandomState(42))


(3000, 100)


In [21]:
test_sample_input = numpy.nan_to_num(test_sample_input)
test_sample_input = preprocessing.normalize(test_sample_input)
print(test_sample_input)

[[0.07883394 0.08614843 0.09752653 ... 0.11296823 0.10321557 0.10321557]
 [0.07843087 0.08202861 0.08562636 ... 0.08418726 0.08562636 0.0892241 ]
 [0.05564605 0.05564605 0.05564605 ... 0.05806544 0.05564605 0.05564605]
 ...
 [0.0854259  0.09449768 0.12927283 ... 0.07862207 0.08089001 0.08391394]
 [0.08663075 0.08051564 0.07541971 ... 0.09172668 0.09070749 0.08764994]
 [0.09387224 0.10405116 0.15946972 ... 0.11649206 0.11423008 0.11649206]]


In [18]:
print("rapidspn generated sample")
spnrp_generated_sample = numpy.nan_to_num(spnrp_generated_sample)
spnrp_generated_sample = preprocessing.normalize(spnrp_generated_sample)
print(spnrp_generated_sample)

rapidspn generated sample
[[0.05962235 0.07293734 0.11445923 ... 0.13909081 0.07353047 0.05736016]
 [0.13186421 0.091682   0.09486358 ... 0.16399904 0.02096803 0.07119478]
 [0.08237079 0.15399169 0.06209839 ... 0.02288907 0.04032107 0.12070352]
 ...
 [0.08576244 0.09897389 0.09247159 ... 0.07702588 0.08458164 0.10584877]
 [0.12756983 0.11521934 0.06095283 ... 0.05695506 0.11943215 0.09867685]
 [0.05916957 0.13495352 0.12602061 ... 0.01695034 0.13156213 0.16607853]]


In [22]:
print("spn_generated_sample")
model_sample_scalar = numpy.nan_to_num(model_sample_scalar)
model_sample_scalar = preprocessing.normalize(model_sample_scalar)
print(model_sample_scalar)

spn_generated_sample
[[0.07955069 0.08384947 0.08131291 ... 0.05951877 0.03984173 0.0473133 ]
 [0.08457751 0.0901082  0.08915548 ... 0.11348926 0.11293529 0.09698265]
 [0.12039372 0.08895889 0.08348317 ... 0.10365702 0.10279714 0.1357615 ]
 ...
 [0.04878585 0.04475499 0.04020378 ... 0.10441877 0.0719556  0.05041404]
 [0.00399915 0.02255681 0.06703027 ... 0.07014284 0.10552232 0.15661025]
 [0.10214947 0.09911666 0.11506003 ... 0.11560872 0.14096421 0.14617445]]
